project:
  name: redis-om-spring
  description: Redis OM Spring
  longDescription: Redis OM Spring provides powerful repository and custom object-mapping abstractions built on top of the powerful Spring Data Redis (SDR) framework.
  links:
    homepage: https://github.com/redis/redis-om-spring
  authors:
    - Brian Sam-Bodden
  license: MIT
  languages:
    java:
      groupId: com.redis.om
      version: '21'
      multiProject: true
  inceptionYear: '2021'
  tags: ['redis', 'spring', 'spring-data', 'object-mapping', 'redisearch', 'json']

signing:
  active: ALWAYS
  armored: true

deploy:
  maven:
    nexus2:
      maven-central-snapshots:
        active: ALWAYS
        url: https://s01.oss.sonatype.org/content/repositories/snapshots/
        closeRepository: false
        releaseRepository: false
        applyMavenCentralRules: false
        stagingRepositories:
          - target/staging-deploy

announce:
  slack:
    active: NEVER

# Define distributions for each module
distributions:
  redis-om-spring:
    artifacts:
      - path: 'redis-om-spring/target/redis-om-spring-{{projectVersion}}.jar'
      - path: 'redis-om-spring/target/redis-om-spring-{{projectVersion}}-sources.jar'
      - path: 'redis-om-spring/target/redis-om-spring-{{projectVersion}}-javadoc.jar'
  redis-om-spring-ai:
    artifacts:
      - path: 'redis-om-spring-ai/target/redis-om-spring-ai-{{projectVersion}}.jar'
      - path: 'redis-om-spring-ai/target/redis-om-spring-ai-{{projectVersion}}-sources.jar'
      - path: 'redis-om-spring-ai/target/redis-om-spring-ai-{{projectVersion}}-javadoc.jar'